export interface SeedItem {
  service: string;
  provider: string;
  providerLabel: string;
  productCode: string;
  name: string;
  amount?: number;
  minAmount?: number;
  maxAmount?: number;
  unitPrice?: number;
  validityDays?: number;
  sortOrder?: number;
}

export const CATALOG_SEED: SeedItem[] = [
  // ---------- Airtime networks ----------
  { service: 'AIRTIME', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn', name: 'MTN Airtime', minAmount: 50, maxAmount: 100000, sortOrder: 1 },
  { service: 'AIRTIME', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo', name: 'Glo Airtime', minAmount: 50, maxAmount: 100000, sortOrder: 2 },
  { service: 'AIRTIME', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airtel', name: 'Airtel Airtime', minAmount: 50, maxAmount: 100000, sortOrder: 3 },
  { service: 'AIRTIME', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'etisalat', name: '9mobile Airtime', minAmount: 50, maxAmount: 100000, sortOrder: 4 },

  // ---------- DATA bundles — REAL VTPass variation codes (live /service-variations) ----------
  // These productCode values are the variation_code VTPass accepts on /pay.
  // The seed re-syncs the DATA catalog against the configured VTPass env at runtime (syncDataPlans).
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-10mb-100', name: '110MB Daily Plan (1 Day)', amount: 100, validityDays: 1, sortOrder: 1 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-230mb-200', name: '230MB Daily Plan (1 Day)', amount: 200, validityDays: 1, sortOrder: 2 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-1500mb-1000', name: '1.5GB Weekly Plan (7 Days)', amount: 1000, validityDays: 7, sortOrder: 3 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-5.5gb-3500', name: '7GB Monthly Plan', amount: 3500, validityDays: 30, sortOrder: 4 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-3.5gb-1500', name: '3.5GB Weekly Plan (7 Days)', amount: 1500, validityDays: 7, sortOrder: 5 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-data-6500', name: '16.5GB + 10mins Monthly Plan', amount: 6500, validityDays: 30, sortOrder: 6 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-20gb-7500', name: '20GB Monthly Plan', amount: 7500, validityDays: 30, sortOrder: 7 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-32gb-11000', name: '36GB Monthly Plan', amount: 11000, validityDays: 30, sortOrder: 8 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-75gb-20000', name: '75GB Monthly Plan', amount: 18000, validityDays: 30, sortOrder: 9 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-2.7gb-2000', name: '2.7GB + 2mins + 2GB All Night Streaming + 200MB YouTube Music, Monthly Plan', amount: 2000, validityDays: 30, sortOrder: 10 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-1800mb-1500', name: '1.8GB + 6mins + 5 SMS, Monthly', amount: 1500, validityDays: 30, sortOrder: 11 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-120gb-24000', name: 'MTN 120GB - 30days', amount: 24000, validityDays: 30, sortOrder: 12 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-480gb-90000', name: '480GB 3-Month Plan', amount: 90000, validityDays: 90, sortOrder: 13 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-1gb-350', name: 'MTN 1GB + 1.5mins - 1 day', amount: 500, validityDays: 1, sortOrder: 14 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-1gb-600', name: '1GB + 1GB YouTube Night + 100MB YouTube Music - Weekly', amount: 800, validityDays: 7, sortOrder: 15 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-xtrabundle-500', name: '600MB Xtra Bundle + 2mins -7 Days', amount: 500, validityDays: 7, sortOrder: 16 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-xtra-1000', name: '2GB + 2 Mins Monthly Plan', amount: 1500, validityDays: 30, sortOrder: 17 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-2-5gb-900', name: 'MTN 2.5GB - 2 days', amount: 900, validityDays: 2, sortOrder: 18 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-150gb-40000', name: '150GB 2-Month Plan', amount: 40000, validityDays: 60, sortOrder: 19 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-11gb-3500', name: 'MTN 11GB - 7 days', amount: 3500, validityDays: 7, sortOrder: 20 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-500mb-ex-350', name: '500MB Daily Plan (1 Day)', amount: 350, validityDays: 1, sortOrder: 21 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-2gb-ex-750', name: '2GB Daily Plan (2 Days)', amount: 750, validityDays: 2, sortOrder: 22 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-8gb-ex-3000', name: 'MTN 10GB + 10mins - 30 days', amount: 4500, validityDays: 30, sortOrder: 23 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-65gb-ex-16000', name: '65GB Monthly Plan (30 Days)', amount: 16000, validityDays: 30, sortOrder: 24 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-500mb-500', name: '500MB + 1GB YouTube (7 Days)', amount: 500, validityDays: 7, sortOrder: 25 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-3.2gb-1000', name: 'MTN 3.2GB - 2 days', amount: 1000, validityDays: 2, sortOrder: 26 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-7gb-3000', name: 'MTN 6GB - 7 days', amount: 2500, validityDays: 7, sortOrder: 27 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-3.5gb-2500', name: 'MTN 3.5GB +5mins Monthly Plan', amount: 2500, validityDays: 30, sortOrder: 28 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-hynetflex-14500-30', name: '60GB Monthly Broadband Plan', amount: 14500, validityDays: 30, sortOrder: 29 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-hynetflex-75000-90', name: '450GB 3-Month Broadband Plan', amount: 75000, validityDays: 90, sortOrder: 30 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-hynetflex-9000-30', name: '30GB Monthly Broadband Plan', amount: 9000, validityDays: 30, sortOrder: 31 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-2.5-750', name: '2.5GB Daily Plan', amount: 750, validityDays: 1, sortOrder: 32 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-20-5000', name: '20GB Weekly Plan', amount: 5000, validityDays: 7, sortOrder: 33 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-7gb-1800', name: 'MTN 7GB - (2 Days)', amount: 1800, validityDays: 2, sortOrder: 34 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-150gb-30000', name: 'MTN 150GB + 2GB daily - 5G Router Data (30 Days)', amount: 30000, validityDays: 30, sortOrder: 35 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-165gb-35000', name: 'MTN 165GB Monthly Data Plan (30 Days)', amount: 35000, validityDays: 30, sortOrder: 36 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-200gb-37500', name: 'MTN 200GB + 5GB Youtube/MSTeams/Zoom - 5G Broadband Data (30 Days)', amount: 37500, validityDays: 30, sortOrder: 37 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-260gb-monthly', name: 'MTN 260GB + 2GB daily upon exhausting main bundle', amount: 45000, validityDays: 30, sortOrder: 38 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-1500gb-yearly', name: 'MTN 1.5TB - Broadband Router', amount: 225000, validityDays: 365, sortOrder: 39 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-6.75gb-3000', name: 'MTN 6.75GB Monthly', amount: 3000, validityDays: 30, sortOrder: 40 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-14.5gb-5000', name: 'MTN 14.5GB Monthly Plan', amount: 5000, validityDays: 30, sortOrder: 41 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-5.5gb-2-1500', name: 'MTN 5.5GB - (2 days)', amount: 1500, validityDays: 2, sortOrder: 42 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-4gb-2-1200', name: 'MTN 4GB - (2 days)', amount: 1200, validityDays: 2, sortOrder: 43 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-3.5gb-1-1000', name: 'MTN 3.5GB - (1 day)', amount: 1000, validityDays: 1, sortOrder: 44 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-34gb-30-10000', name: 'MTN 34GB - (30 days)', amount: 10000, validityDays: 30, sortOrder: 45 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-15gb-7d-4000', name: '15GB Weekly Plan', amount: 4000, validityDays: 7, sortOrder: 46 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-12gb-7d-4500', name: '12.5GB 14 days', amount: 4500, validityDays: 14, sortOrder: 47 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-14d-18gb-6000', name: '18GB - 14 days', amount: 6000, validityDays: 14, sortOrder: 48 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-14d-28gb-8000', name: '28GB - 14 days', amount: 8000, validityDays: 14, sortOrder: 49 },
  { service: 'DATA', provider: 'MTN', providerLabel: 'MTN Nigeria', productCode: 'mtn-14d-40gb-10000', name: '40GB - 14 days', amount: 10000, validityDays: 14, sortOrder: 50 },

  // ---------- GLO data bundles (serviceID: glo-data) ----------
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-daily-50', name: '40MB + 5MB Night - 1 Day', amount: 50, validityDays: 1, sortOrder: 1 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-daily-100', name: '120MB + 5MB Night - 1 Day', amount: 100, validityDays: 1, sortOrder: 2 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-2days-200', name: '250MB + 25MB Night - 2 Days', amount: 200, validityDays: 2, sortOrder: 3 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-1000', name: '1.1GB + 1.5GB Night - 30 Days', amount: 1000, validityDays: 30, sortOrder: 4 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-1500', name: '2.2GB + 3GB - 30 Days', amount: 1500, validityDays: 30, sortOrder: 5 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-2000', name: '3.25GB + 3GB Night - 30 Days', amount: 2000, validityDays: 30, sortOrder: 6 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-2500', name: '4.25GB + 3GB Night - 30 Days', amount: 2500, validityDays: 30, sortOrder: 7 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-3000', name: '8.5GB + 2GB Night - 30 Days', amount: 3000, validityDays: 30, sortOrder: 8 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-4000', name: '10.5GB + 2GB Night - 30 Days', amount: 4000, validityDays: 30, sortOrder: 9 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-5000', name: '14.5GB + 2.5GB Night - 30 Days', amount: 5000, validityDays: 30, sortOrder: 10 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-8000', name: '26GB + 2GB - 30 Days', amount: 8000, validityDays: 30, sortOrder: 11 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-monthly-10000', name: '38GB + 4GB Night - 30 Days', amount: 10000, validityDays: 30, sortOrder: 12 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-sunday-200', name: '875MB 1 Day - Weekend', amount: 200, validityDays: 1, sortOrder: 13 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-special-500', name: '1GB + 1GB Night - 2 Days Special', amount: 500, validityDays: 2, sortOrder: 14 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-special-1500', name: '4GB + 2GB Night - 7 Days - Special', amount: 1500, validityDays: 7, sortOrder: 15 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-weekend-500', name: '2.5GB 2 Days - Weekend', amount: 500, validityDays: 2, sortOrder: 16 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-mega-30000', name: '165GB 30 Days - Mega', amount: 30000, validityDays: 30, sortOrder: 17 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-mega-40000', name: '220GB 30 Days - Mega Oneoff', amount: 40000, validityDays: 30, sortOrder: 18 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-mega-50000', name: '310GB 60 Days - Mega', amount: 50000, validityDays: 60, sortOrder: 19 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-mega-60000', name: '355GB 90 Days - Mega', amount: 60000, validityDays: 90, sortOrder: 20 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-mega-75000', name: '475GB 90 Days - Mega Oneoff', amount: 75000, validityDays: 90, sortOrder: 21 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-tv-150', name: 'Glo TV VOD 500 MB 3days Oneoff', amount: 150, validityDays: 3, sortOrder: 22 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-tv-450', name: 'Glo TV VOD 2GB 7days Oneoff', amount: 450, validityDays: 7, sortOrder: 23 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-tv-1400', name: 'Glo TV VOD 6GB 30days', amount: 1400, validityDays: 30, sortOrder: 24 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-tv-900', name: 'Glo TV Lite 2GB 7 Days', amount: 900, validityDays: 7, sortOrder: 25 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-tv-3200', name: 'Glo TV Max 6 GB 30 Days', amount: 3200, validityDays: 30, sortOrder: 26 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-social-oneoff-100', name: '300MB - GloMyG 1 Day', amount: 100, validityDays: 1, sortOrder: 27 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-social-oneoff-300', name: 'Glo MyG 1 GB 3 Days OneOff (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)', amount: 300, validityDays: 3, sortOrder: 28 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-social-oneoff-500', name: 'Glo MyG 1.5 GB 7 Days (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)', amount: 500, validityDays: 7, sortOrder: 29 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-social-oneoff-1000', name: 'Glo MyG 3.5 GB 30 Days (Whatsapp, Instagram, Snapchat, Boomplay, Audiomac, GloTV, Tiktok)', amount: 1000, validityDays: 30, sortOrder: 30 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-100', name: '240MB + 5MB Night - 1 Day - Camp-Boost', amount: 100, validityDays: 1, sortOrder: 31 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-200', name: '500MB + 25MB Night - 2 Days - Camp-Boost', amount: 200, validityDays: 2, sortOrder: 32 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-500', name: '1.1GB + 1GB Night - 7 Days - Camp-Boost', amount: 500, validityDays: 7, sortOrder: 33 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-1000', name: '2.2GB + 2GB Night - 30 Days - Camp-Boost', amount: 1000, validityDays: 30, sortOrder: 34 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-2000', name: '6.5GB + 3.5GB - 30 Days - Camp-Boost', amount: 2000, validityDays: 30, sortOrder: 35 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-campus-booster-5000', name: '29GB + 3GB Night - 30 Days - Camp-Boost', amount: 5000, validityDays: 30, sortOrder: 36 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-295', name: '1GB (Best Value) - 3 days', amount: 330, validityDays: 3, sortOrder: 37 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-890', name: '3GB (Best Value) - 3 days', amount: 1005, validityDays: 3, sortOrder: 38 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-1485', name: '3GB (Best Value) - 30 days', amount: 1485, validityDays: 30, sortOrder: 52 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-345', name: '1GB (Best Value) - 7 days', amount: 366, validityDays: 7, sortOrder: 40 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-1040', name: '3GB (Best Value) - 7 days', amount: 1110, validityDays: 7, sortOrder: 41 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-1730', name: '5GB (Best Value) - 14 days Night plan', amount: 1875, validityDays: 14, sortOrder: 45 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-350', name: '1GB (Best Value) - 14 days Night plan', amount: 366, validityDays: 14, sortOrder: 43 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-1040-14', name: '3GB (Best Value) - 14 days Night plan', amount: 1110, validityDays: 14, sortOrder: 44 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-3460', name: '10GB (Best Value) - 14 days Night plan', amount: 3725, validityDays: 14, sortOrder: 46 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-99', name: '200MB (Best Value) - 14 days', amount: 99, validityDays: 14, sortOrder: 47 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-250', name: '500MB (Best Value) - 14 days', amount: 250, validityDays: 14, sortOrder: 48 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-250-30', name: '500MB (Best Value) - 30 Days', amount: 250, validityDays: 30, sortOrder: 49 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-495', name: '1GB (Best Value) - 30 days', amount: 495, validityDays: 30, sortOrder: 50 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-990', name: '2GB (Best Value) - 30 days', amount: 990, validityDays: 30, sortOrder: 51 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-2475', name: '5GB (Best Value) - 30 days', amount: 2475, validityDays: 30, sortOrder: 53 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-dg-4950', name: '10GB (Best Value) - 30 days', amount: 4950, validityDays: 30, sortOrder: 54 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-750-14', name: '1.1GB 14 Days', amount: 750, validityDays: 14, sortOrder: 55 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-1000-7days', name: '1.7GB + 2GB Night - 7 Days', amount: 1000, validityDays: 7, sortOrder: 56 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-2000-7days', name: '6.5GB + 2.5GB - 7 Days', amount: 2000, validityDays: 7, sortOrder: 57 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-5000-7days', name: '22GB + 2GB Night - 7 Days', amount: 5000, validityDays: 7, sortOrder: 58 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-6000-30days', name: '18.5GB + 2GB Night - 30 Days', amount: 6000, validityDays: 30, sortOrder: 59 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-15000-30days', name: '62GB + 2GB - 30 Days', amount: 15000, validityDays: 30, sortOrder: 60 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-20000-30days', name: '105GB + 2GB - 30 Days', amount: 20000, validityDays: 30, sortOrder: 61 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-350-special-1day', name: '1GB 1 Day - Special', amount: 350, validityDays: 1, sortOrder: 62 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-600-special-2days', name: '1.55GB + 2GB Night - 2 Days - Special', amount: 600, validityDays: 2, sortOrder: 63 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-1000-special-2days', name: '3.1GB + 2GB - 2 Days - Special', amount: 1000, validityDays: 2, sortOrder: 64 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-25000-mega-30days', name: '135GB 30 Days - Mega Oneoff', amount: 25000, validityDays: 30, sortOrder: 65 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-yearly-mega', name: '1000GB Yearly - Mega Oneoff', amount: 150000, validityDays: 365, sortOrder: 66 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-social-50-3days', name: '135MB 3 Days - Social Bundles', amount: 50, validityDays: 3, sortOrder: 67 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-special-100-7days', name: '335MB 7 Days - Social Bundles', amount: 100, validityDays: 7, sortOrder: 68 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-special-300-10days', name: '1.1GB 10 Days - Social Bundles', amount: 300, validityDays: 10, sortOrder: 69 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-special-500-15days', name: '1.8GB 15 Days - Social Bundles', amount: 500, validityDays: 15, sortOrder: 70 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-night-60-1day', name: '350MB Night', amount: 60, validityDays: 30, sortOrder: 71 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-night-120-1day', name: '750MB Night', amount: 120, validityDays: 30, sortOrder: 72 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-500mb-200-oneoff', name: '500MB 1 Day - Oneoff', amount: 200, validityDays: 1, sortOrder: 73 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-1000mb-300-oneoff', name: '1GB 1 Day - Oneoff', amount: 300, validityDays: 1, sortOrder: 74 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-always-on-2000', name: '6.1GB (410MB per day) 15 Days - Always On', amount: 2000, validityDays: 15, sortOrder: 75 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-always-on-3500', name: '15GB (500MB per day) 30 Days - Always On', amount: 3500, validityDays: 30, sortOrder: 76 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-always-on-5000', name: '30GB (1GB per day) 30 Days - Always On', amount: 5000, validityDays: 30, sortOrder: 77 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-always-on-7000', name: '45GB (1.5 per day) 30 Days - Always On', amount: 7000, validityDays: 30, sortOrder: 78 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-youtube-250', name: '1GB 1 Day - Youtube Special', amount: 250, validityDays: 1, sortOrder: 79 },
  { service: 'DATA', provider: 'GLO', providerLabel: 'Globacom', productCode: 'glo-youtube-600', name: '3GB 2 Days - Youtube Special', amount: 600, validityDays: 2, sortOrder: 80 },

  // ---------- AIRTEL data bundles (serviceID: airtel-data) ----------
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-50', name: '250MB Night Plan (12 - 5 AM) - 1Day', amount: 50, validityDays: 1, sortOrder: 1 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-100', name: '200MB Social Plan (2 Days) - 1Day', amount: 100, validityDays: 2, sortOrder: 2 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-200', name: '230MB Daily Plan (2 Days) - 200MB - 1Day', amount: 200, validityDays: 2, sortOrder: 3 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-daily-100', name: 'Airtel Data - 110MB - 1 Day', amount: 100, validityDays: 1, sortOrder: 4 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-500', name: '500MB Weekly Plan (7 Days)', amount: 500, validityDays: 7, sortOrder: 5 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-1000-7', name: '1.5GB Weekly Plan + Youtube & Social Plans (7 Days)', amount: 1000, validityDays: 7, sortOrder: 6 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-1500-7', name: '3.5GB Weekly Plan + Youtube & Social Platform (7 Days)', amount: 1500, validityDays: 7, sortOrder: 7 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-2000', name: '3GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 2000, validityDays: 30, sortOrder: 8 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-3000', name: '8GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 3000, validityDays: 30, sortOrder: 9 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-4000', name: '10GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 4000, validityDays: 30, sortOrder: 10 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-5000', name: '13GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 5000, validityDays: 30, sortOrder: 11 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-1500-2', name: '5GB Binge Plan + Youtube & Social Platforms Data (2 Day)', amount: 1500, validityDays: 2, sortOrder: 12 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-10000', name: '35GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 10000, validityDays: 30, sortOrder: 13 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-15000', name: '60GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 15000, validityDays: 30, sortOrder: 14 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-40000', name: '210GB Data (30 Days)', amount: 40000, validityDays: 30, sortOrder: 15 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-60000', name: '350GB Monthly Plan + Youtube & Social Plan (120 Days)', amount: 60000, validityDays: 120, sortOrder: 16 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-100000', name: '680GB Data (365 Days)', amount: 100000, validityDays: 365, sortOrder: 17 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-20000', name: '100GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 20000, validityDays: 30, sortOrder: 18 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-2500', name: '4GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 2500, validityDays: 30, sortOrder: 19 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-8000', name: '25GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 8000, validityDays: 30, sortOrder: 20 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-30000', name: '160GB Monthly Plan (30 Days)', amount: 30000, validityDays: 30, sortOrder: 21 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-50000', name: '200GB Monthly Plan (90 Days)', amount: 50000, validityDays: 90, sortOrder: 22 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-600', name: '1.5GB Binge Plan + Youtube & Social Plan Data (2 Days)', amount: 600, validityDays: 2, sortOrder: 23 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-1000-2', name: '4GB Plan + 2GB YouTube Night + 200MB YT/IG/TT(2 Days)', amount: 1000, validityDays: 2, sortOrder: 24 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-3000-7', name: '10GB Weekly Plan + Youtube & Social Platform (7 Days)', amount: 3000, validityDays: 7, sortOrder: 25 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-5000-7', name: '18GB Weekly Plan + Youtube & Social Platform (7 Days)', amount: 5000, validityDays: 7, sortOrder: 26 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-binge-500-1', name: 'Binge Plan 1GB', amount: 500, validityDays: 30, sortOrder: 27 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-800-7', name: '1GB Weekly Plan (7 Days)', amount: 800, validityDays: 7, sortOrder: 28 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-6000-30', name: '18GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 6000, validityDays: 30, sortOrder: 29 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-75-1', name: '75MB Daily Plan (1 Day)', amount: 75, validityDays: 1, sortOrder: 30 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-300-1', name: '300MB Daily Plan (1 Day)', amount: 300, validityDays: 1, sortOrder: 31 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-social-300-3', name: '1GB Social Plan Plan (3 Days)', amount: 300, validityDays: 3, sortOrder: 32 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-750-2', name: '2GB Binge Plan + Youtube & Social Plan Data (2 Days)', amount: 750, validityDays: 2, sortOrder: 33 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-1500-30', name: '2GB Monthly Plan + Youtube & Social Plan (30 Days)', amount: 1500, validityDays: 30, sortOrder: 34 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-2500-7', name: '6GB Weekly Plan + Youtube & Social Platform (7 Days)', amount: 2500, validityDays: 7, sortOrder: 35 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-5000-30', name: '13GB MIFI 5 Data - MiFi Only (30 Days)', amount: 5000, validityDays: 30, sortOrder: 36 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-10000-30', name: '35GB MIFI 10 Data - MiFi Only (30 Days)', amount: 10000, validityDays: 30, sortOrder: 37 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-15000-30', name: '60GB MIFI 15 Data - MiFi Only (30 Days)', amount: 15000, validityDays: 30, sortOrder: 38 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-20000-30', name: '100GB Unlimited Uiltra 20 - Router Only (30 Days)', amount: 20000, validityDays: 30, sortOrder: 39 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-30000-30', name: 'Unlimited 20MBPS Data - Router Only (30 Days)', amount: 30000, validityDays: 30, sortOrder: 40 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-50000-30', name: 'Unlimited 60MBPS Data - Router Only (30 Days)', amount: 50000, validityDays: 30, sortOrder: 41 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-80000-90', name: 'Unlimited 60MBPS Data - Router Only (90 Days)', amount: 80000, validityDays: 90, sortOrder: 42 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-135000-90', name: 'Unlimited 60MBPS Data - Router Only (90 Days)', amount: 135000, validityDays: 90, sortOrder: 43 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-mifi-150000-120', name: 'Unlimited 20MBPS Data - Router Only (120 Days)', amount: 150000, validityDays: 120, sortOrder: 44 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-social-500-7', name: '1.5GB Social Plan', amount: 500, validityDays: 30, sortOrder: 45 },
  { service: 'DATA', provider: 'AIRTEL', providerLabel: 'Airtel Nigeria', productCode: 'airt-350-500', name: '500MB Daily Plan (2 Days) - 500MB - 2 Days', amount: 350, validityDays: 2, sortOrder: 46 },

  // ---------- 9MOBILE data bundles (serviceID: etisalat-data) ----------
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-100', name: 'T2 83MB - 1 day', amount: 100, validityDays: 1, sortOrder: 1 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-150', name: 'T2 150MB + 100MB Night Data - 1 day', amount: 150, validityDays: 1, sortOrder: 2 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-500', name: 'T2 650MB - 3 days', amount: 500, validityDays: 3, sortOrder: 3 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-1000', name: '9mobile 2GB - 30 Days', amount: 1000, validityDays: 30, sortOrder: 4 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-4000', name: 'T2 8.4GB - 30 days', amount: 4000, validityDays: 30, sortOrder: 5 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-2000', name: 'T2 4.5GB - 30 Days', amount: 2000, validityDays: 30, sortOrder: 6 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-5000', name: 'T2 11.4GB - 30 Days', amount: 5000, validityDays: 30, sortOrder: 7 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-3000', name: 'T2 6.2G - 30 days', amount: 3000, validityDays: 30, sortOrder: 8 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-1200', name: 'T2 2.3GB - 30 Days', amount: 1200, validityDays: 30, sortOrder: 9 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-50', name: 'T2 40MB - 1 day', amount: 50, validityDays: 1, sortOrder: 10 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 'eti-2500', name: 'T2 5.2GB - 30 days', amount: 2500, validityDays: 30, sortOrder: 11 },
  { service: 'DATA', provider: '9MOBILE', providerLabel: '9mobile', productCode: 't2-250mb-200', name: 'T2 - 250MB Anytime Data Plan (7 Days)', amount: 200, validityDays: 7, sortOrder: 12 },

  // ---------- Cable TV ----------
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-padi', name: 'DStv Padi', amount: 3150, sortOrder: 1 },
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-yanga', name: 'DStv Yanga', amount: 5000, sortOrder: 2 },
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-confam', name: 'DStv Confam', amount: 7000, sortOrder: 3 },
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-compact', name: 'DStv Compact', amount: 9000, sortOrder: 4 },
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-compactplus', name: 'DStv Compact Plus', amount: 15000, sortOrder: 5 },
  { service: 'CABLE', provider: 'DSTV', providerLabel: 'DStv', productCode: 'dstv-premium', name: 'DStv Premium', amount: 21000, sortOrder: 6 },
  { service: 'CABLE', provider: 'GOTV', providerLabel: 'GOtv', productCode: 'gotv-smallie', name: 'GOtv Smallie', amount: 2000, sortOrder: 1 },
  { service: 'CABLE', provider: 'GOTV', providerLabel: 'GOtv', productCode: 'gotv-jinja', name: 'GOtv Jinja', amount: 3000, sortOrder: 2 },
  { service: 'CABLE', provider: 'GOTV', providerLabel: 'GOtv', productCode: 'gotv-jolli', name: 'GOtv Jolli', amount: 4000, sortOrder: 3 },
  { service: 'CABLE', provider: 'GOTV', providerLabel: 'GOtv', productCode: 'gotv-max', name: 'GOtv Max', amount: 5000, sortOrder: 4 },
  { service: 'CABLE', provider: 'STARTIMES', providerLabel: 'StarTimes', productCode: 'startimes-nova', name: 'StarTimes Nova', amount: 1300, sortOrder: 1 },
  { service: 'CABLE', provider: 'STARTIMES', providerLabel: 'StarTimes', productCode: 'startimes-basic', name: 'StarTimes Basic', amount: 2000, sortOrder: 2 },
  { service: 'CABLE', provider: 'STARTIMES', providerLabel: 'StarTimes', productCode: 'startimes-classic', name: 'StarTimes Classic', amount: 3500, sortOrder: 3 },
  { service: 'CABLE', provider: 'STARTIMES', providerLabel: 'StarTimes', productCode: 'startimes-asia', name: 'StarTimes Asia', amount: 4500, sortOrder: 4 },

  // ---------- Electricity Discos (provider/productCode = VTPass serviceID) ----------
  { service: 'ELECTRICITY', provider: 'ikeja-electric', providerLabel: 'Ikeja Electric (IKEDC)', productCode: 'ikeja-electric', name: 'IKEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 1 },
  { service: 'ELECTRICITY', provider: 'eko-electric', providerLabel: 'Eko Electric (EKEDC)', productCode: 'eko-electric', name: 'EKEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 2 },
  { service: 'ELECTRICITY', provider: 'abuja-electric', providerLabel: 'Abuja Electric (AEDC)', productCode: 'abuja-electric', name: 'AEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 3 },
  { service: 'ELECTRICITY', provider: 'portharcourt-electric', providerLabel: 'Port Harcourt Electric (PHED)', productCode: 'portharcourt-electric', name: 'PHED Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 4 },
  { service: 'ELECTRICITY', provider: 'ibadan-electric', providerLabel: 'Ibadan Electric (IBEDC)', productCode: 'ibadan-electric', name: 'IBEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 5 },
  { service: 'ELECTRICITY', provider: 'enugu-electric', providerLabel: 'Enugu Electric (EEDC)', productCode: 'enugu-electric', name: 'EEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 6 },
  { service: 'ELECTRICITY', provider: 'kaduna-electric', providerLabel: 'Kaduna Electric (KAEDCO)', productCode: 'kaduna-electric', name: 'KAEDCO Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 7 },
  { service: 'ELECTRICITY', provider: 'kano-electric', providerLabel: 'Kano Electric (KEDCO)', productCode: 'kano-electric', name: 'KEDCO Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 8 },
  { service: 'ELECTRICITY', provider: 'jos-electric', providerLabel: 'Jos Electric (JED)', productCode: 'jos-electric', name: 'JED Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 9 },
  { service: 'ELECTRICITY', provider: 'benin-electric', providerLabel: 'Benin Electric (BEDC)', productCode: 'benin-electric', name: 'BEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 10 },
  { service: 'ELECTRICITY', provider: 'aba-electric', providerLabel: 'Aba Electric (APLE)', productCode: 'aba-electric', name: 'APLE Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 11 },
  { service: 'ELECTRICITY', provider: 'yola-electric', providerLabel: 'Yola Electric (YEDC)', productCode: 'yola-electric', name: 'YEDC Prepaid / Postpaid', minAmount: 500, maxAmount: 1000000, sortOrder: 12 },

  // ---------- WAEC ----------
  // amounts mirror VTPass variation_amount (waec -> waecdirect = 900, waec-registration -> waec-registraion = 14450).
  // The seed re-syncs these against VTPass live at runtime (syncWaecPricing in seed.ts), so keep them in sync.
  { service: 'WAEC', provider: 'WAEC', providerLabel: 'WAEC', productCode: 'waec-result-checker', name: 'WAEC Result Checker PIN', amount: 900, sortOrder: 1 },
  { service: 'WAEC', provider: 'WAEC', providerLabel: 'WAEC', productCode: 'waec-registration', name: 'WAEC Registration (Full)', amount: 14450, sortOrder: 2 },

  // ---------- JAMB PIN Vending (serviceID: jamb) ----------
  // amounts mirror VTPass variation_amount (utme-mock = 7700, utme-no-mock = 6200).
  // The seed re-syncs these against VTPass live at runtime (syncJambPricing in seed.ts), so keep them in sync.
  { service: 'JAMB', provider: 'JAMB', providerLabel: 'JAMB', productCode: 'utme-mock', name: 'UTME PIN (with mock)', amount: 7700, sortOrder: 1 },
  { service: 'JAMB', provider: 'JAMB', providerLabel: 'JAMB', productCode: 'utme-no-mock', name: 'UTME PIN (without mock)', amount: 6200, sortOrder: 2 },

  // ---------- Bulk SMS ----------
  { service: 'SMS', provider: 'VTPASS', providerLabel: 'VTPass Messaging', productCode: 'bulk-sms', name: 'Bulk SMS (sender ID)', unitPrice: 2.5, minAmount: 1, maxAmount: 10000, sortOrder: 1 },
];

